services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-fcg
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
      - MSSQL_PID=Developer
      - MSSQL_DATABASE=fcg_database
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - network-fcg
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourPassword123" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  seq:
    image: datalust/seq
    container_name: seq-fcg
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=YourPassword123   
    ports:
      - "5341:5341"  
      - "5342:80"   
    networks:
      - network-fcg

  api-fcg:
    build:
      context: .
      dockerfile: src/FCG.WebApi/Dockerfile
    container_name: api-fcg
    depends_on:
      sqlserver:
        condition: service_healthy
      seq:
        condition: service_started
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=fcg_database;User Id=sa;Password=YourPassword123;TrustServerCertificate=True;
      - Serilog__SeqUrl=http://seq:5341
    networks:
      - network-fcg
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  network-fcg:
    driver: bridge