// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FCG.FunctionalTests.Features.Game
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetAllGamesUseCaseFeature : object, Xunit.IClassFixture<GetAllGamesUseCaseFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features/Game", "GetAllGamesUseCase", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetAllGames.feature"
#line hidden
        
        public GetAllGamesUseCaseFeature(GetAllGamesUseCaseFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listagem de todos os jogos com paginacao")]
        [Xunit.TraitAttribute("FeatureTitle", "GetAllGamesUseCase")]
        [Xunit.TraitAttribute("Description", "Listagem de todos os jogos com paginacao")]
        [Xunit.TraitAttribute("Category", "regressivo")]
        [Xunit.TraitAttribute("Category", "aceite")]
        public async System.Threading.Tasks.Task ListagemDeTodosOsJogosComPaginacao()
        {
            string[] tagsOfScenario = new string[] {
                    "regressivo",
                    "aceite"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listagem de todos os jogos com paginacao", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("que existem jogos cadastrados no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 6
 await testRunner.WhenAsync("o usuario solicita a listagem de jogos com paginacao", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 7
 await testRunner.ThenAsync("o sistema deve retornar a lista de jogos paginada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listagem de jogos com filtro por nome")]
        [Xunit.TraitAttribute("FeatureTitle", "GetAllGamesUseCase")]
        [Xunit.TraitAttribute("Description", "Listagem de jogos com filtro por nome")]
        [Xunit.TraitAttribute("Category", "regressivo")]
        [Xunit.TraitAttribute("Category", "aceite")]
        public async System.Threading.Tasks.Task ListagemDeJogosComFiltroPorNome()
        {
            string[] tagsOfScenario = new string[] {
                    "regressivo",
                    "aceite"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listagem de jogos com filtro por nome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
 await testRunner.GivenAsync("que existem jogos cadastrados no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 12
 await testRunner.WhenAsync("o usuario solicita a listagem de jogos filtrando por nome", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 13
 await testRunner.ThenAsync("o sistema deve retornar apenas os jogos que correspondem ao filtro de nome", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listagem de jogos com filtro por categoria")]
        [Xunit.TraitAttribute("FeatureTitle", "GetAllGamesUseCase")]
        [Xunit.TraitAttribute("Description", "Listagem de jogos com filtro por categoria")]
        [Xunit.TraitAttribute("Category", "regressivo")]
        [Xunit.TraitAttribute("Category", "aceite")]
        public async System.Threading.Tasks.Task ListagemDeJogosComFiltroPorCategoria()
        {
            string[] tagsOfScenario = new string[] {
                    "regressivo",
                    "aceite"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listagem de jogos com filtro por categoria", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
 await testRunner.GivenAsync("que existem jogos cadastrados no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 18
 await testRunner.WhenAsync("o usuario solicita a listagem de jogos filtrando por categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 19
 await testRunner.ThenAsync("o sistema deve retornar apenas os jogos da categoria especificada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listagem de jogos com filtro por faixa de preco")]
        [Xunit.TraitAttribute("FeatureTitle", "GetAllGamesUseCase")]
        [Xunit.TraitAttribute("Description", "Listagem de jogos com filtro por faixa de preco")]
        [Xunit.TraitAttribute("Category", "regressivo")]
        [Xunit.TraitAttribute("Category", "aceite")]
        public async System.Threading.Tasks.Task ListagemDeJogosComFiltroPorFaixaDePreco()
        {
            string[] tagsOfScenario = new string[] {
                    "regressivo",
                    "aceite"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listagem de jogos com filtro por faixa de preco", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
 await testRunner.GivenAsync("que existem jogos cadastrados no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 24
 await testRunner.WhenAsync("o usuario solicita a listagem de jogos filtrando por faixa de preco", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 25
 await testRunner.ThenAsync("o sistema deve retornar apenas os jogos dentro da faixa de preco", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listagem de jogos com multiplos filtros")]
        [Xunit.TraitAttribute("FeatureTitle", "GetAllGamesUseCase")]
        [Xunit.TraitAttribute("Description", "Listagem de jogos com multiplos filtros")]
        [Xunit.TraitAttribute("Category", "regressivo")]
        [Xunit.TraitAttribute("Category", "aceite")]
        public async System.Threading.Tasks.Task ListagemDeJogosComMultiplosFiltros()
        {
            string[] tagsOfScenario = new string[] {
                    "regressivo",
                    "aceite"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listagem de jogos com multiplos filtros", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
 await testRunner.GivenAsync("que existem jogos cadastrados no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 30
 await testRunner.WhenAsync("o usuario solicita a listagem de jogos com multiplos filtros aplicados", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 31
 await testRunner.ThenAsync("o sistema deve retornar apenas os jogos que atendem a todos os filtros", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GetAllGamesUseCaseFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GetAllGamesUseCaseFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
